<SigninWindow>:
    orientation: "vertical"
    spacing: 10

    BoxLayout:
        size_hint_y: None
        height: 50
        Label:
            text: "Access Control"
            bold: True
            size_hint_x: .9
        Button:
            text: "x"
            size_hint_x: .1
    BoxLayout:
        orientation: "vertical"
        TextInput:
            hint_text: "Username"
        TextInput:
            hint_text: "Password"
    Button:
        text: "Sign In"
